export const SERVER_URL = "http://localhost:8000"
export const APPOINTMENT_URL = "http://localhost:8000/v1/appointment"
export const CONFERENCE_URL = "http://localhost:8000/v1/conference"
export const REQUESTS_URL = "http://localhost:8000/v1/requests"
export const APPOINTMENT_SIGNIN_URL = "http://localhost:8000/v1/auth/appointment/google"
export const CONFERENCE_SIGNIN_URL = "http://localhost:8000/v1/auth/conference/google"
export const USER_URL = "http://localhost:8000/v1/user"
export const DLT_URL = "http://localhost:8000/v1/dlt"